lesson 1 add modals
aigul-ermak/projest-second pull request #1
Opened 2022-05-07 03:56 UTC by aigul-ermak

2022-05-07 08:19 UTC, andrey-kudinov requested changes
Всё отлично!
Есть пара небольших замечаний

2022-05-07 08:19 UTC, andrey-kudinov commented on src/modals/modals.ts
> +            windows.forEach(window => window.style.display = 'none');
По всей видимости этот функционал закрытия окна повторяется
Его можно вынести в отдельную функцию
И так же переиспользовать при закрытии по клавише escape

2022-05-07 08:19 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                viewModal({modalProperty: 'none'});
Здесь вроде бы в других событиях закрытия окна больше действий

2022-05-07 08:19 UTC, andrey-kudinov commented on src/modals/modals.ts
> +                    let scroll = calcScroll();
Хорошо было бы выработать привычку переменные объявлять чз **const**

2022-05-09 03:50 UTC, aigul-ermak commented on src/modals/modals.ts
> +                    let scroll = calcScroll();
блин

2022-05-09 12:55 UTC, merged